//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        [Required]
        [StringLength(20,MinimumLength =3)]
        [RegularExpression(@"^[A-Z][a-z]*$",ErrorMessage ="Name should not contain special characters")]
        public string Name { get; set; }
        [Required]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$",ErrorMessage ="Email should be [name@domain.extension]")]
        public string Email { get; set; }
        [Required]
        [RegularExpression(@"^[6-9][0-9]{9}$",ErrorMessage ="Mobile number starts from 6-9 and followed by 9 digits")]
        public Nullable<long> MobileNo { get; set; }
        [Required]

        public string Adress { get; set; }
        [Required]
        [RegularExpression(@"^[m]|[f]*$", ErrorMessage = "Gender should be 'm' or 'f'")]
        public string Gender { get; set; }
        [Required]
        public string UserId { get; set; }
        [Required]
        public string password { get; set; }
    }
}
