//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class passenger
    {
        [Required]
        [StringLength(20,MinimumLength =3)]
        [RegularExpression(@"^[A-z][a-z]*$",ErrorMessage ="PassengerName should not contain the special characters")]
        public string Name { get; set; }
        [Required]
        [RegularExpression(@"^(?:1[01][0-9]|120|1[7-9]|[2-9][0-9])$", ErrorMessage ="PassengerAge should be greater than 18 ")]
        public Nullable<int> Age { get; set; }
        [Required]
        [RegularExpression(@"^[m]|[f]*$",ErrorMessage ="Gender should be 'm' or 'f'")]
        public string Gender { get; set; }
        public int Sno { get; set; }
    }
}
