//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public string Source { get; set; }
        public string Destination { get; set; }
        public string TrainName { get; set; }
        public Nullable<int> TrainNo { get; set; }
        public Nullable<int> ACFare { get; set; }
        public Nullable<int> SLFare { get; set; }
        public Nullable<int> SSFare { get; set; }
        public Nullable<int> ACAvailable { get; set; }
        public Nullable<int> SLAvailable { get; set; }
        public Nullable<int> SSAvailable { get; set; }
        public int sno { get; set; }
    }
}
